
name: air_bnb_TEST
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install Flask Flask-Testing
          # pip install pymongo
          pip install python-dotenv
        working-directory: ${{ github.workspace }}

      - name: Set PYTHONPATH
        run: echo "export PYTHONPATH=$(pwd):$(pwd)/src" >> $GITHUB_ENV

      - name: Print working directory
        run: ls -R $GITHUB_WORKSPACE

      - name: Set environment variables
        run: |
          echo "MONGODB_URI=$MONGODB_URI" >> $GITHUB_ENV
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE/tests
          pytest test_login.py
          pytest test_choices.py
          pytest test_integration.py
        env:
          PYTHONPATH: $GITHUB_WORKSPACE/tests
